language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- sudo apt-get install build-essential gcc-multilib cmake python python-setuptools libffi-dev
- cd deepstate
- mkdir build
- cd build
- cmake ..
- make
- make install
script:
- deepstate-manticore examples/IntegerArithmetic
