language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- pip install pyflakes
- sudo apt-get -y update
- sudo apt-get -y install build-essential gcc-multilib cmake python python-pip python-setuptools libffi-dev
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo pip install manticore
- mkdir build
- cd build
- cmake ..
- make
- python setup.py install
- cd ..
env:
- TASK=ANGR DEEPSTATE_CMD=deepstate-angr
- TASK=MANTICORE DEEPSTATE_CMD=deepstate-manticore
script:
- pyflakes tests/*.py
- nosetests --verbose
