language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- pip install pyflakes
- sudo apt-get -y update
- sudo apt-get -y install build-essential gcc-multilib cmake python python-setuptools libffi-dev
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then git clone https://github.com/Z3Prover/z3.git; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then cd z3; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then python scripts/mk_make.py; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then cd build; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then make; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo make install; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then cd ../..; fi
- mkdir build
- cd build
- cmake ..
- make
- python setup.py install
- cd ..
env:
- TASK=ANGR DEEPSTATE_CMD=deepstate-angr
- TASK=MANTICORE DEEPSTATE_CMD=deepstate-manticore
script:
- pyflakes tests/*.py
- nosetests --verbose
