language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- pip install pyflakes
- sudo apt-get -y update
- sudo apt-get -y install build-essential gcc-multilib cmake python python-pip python-setuptools libffi-dev
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo pip install -U pip ; sudo pip install manticore ; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo pip uninstall -y Manticore || echo "Manticore not cached" ; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo pip install https://github.com/trailofbits/manticore/archive/master.zip ; fi
- mkdir build
- cd build
- cmake ..
- make
- python setup.py install
- cd ..
env:
- TASK=PRIMES DEEPSTATE_CMD=deepstate-angr
- TASK=PRIMES DEEPSTATE_CMD=deepstate-manticore
- TASK=ONEOF DEEPSTATE_CMD=deepstate-angr
- TASK=ONEOF DEEPSTATE_CMD=deepstate-manticore
- TASK=ARITHMETIC DEEPSTATE_CMD=deepstate-angr
- TASK=ARITHMETIC DEEPSTATE_CMD=deepstate-manticore
script:
- pyflakes bin/deepstate/*.py
- pyflakes tests/*.py
- nosetests --verbose
