language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- pip install pyflakes
- sudo apt-get -y update
- sudo apt-get -y install build-essential gcc-multilib cmake python python-pip python-setuptools libffi-dev
- sudo pip install -U pip ; sudo pip install manticore
- sudo pip uninstall -y Manticore || echo "Manticore not cached"
- sudo pip install https://github.com/trailofbits/manticore/archive/master.zip
- mkdir build
- cd build
- cmake ..
- make
- python setup.py install
- cd ..
env:
- TASK=ARITHMETIC
- TASK=CRASH
- TASK=FIXTURE
- TASK=KLEE
- TASK=LISTS
- TASK=ONEOF
- TASK=OVERFLOW
- TASK=PRIMES
- TASK=STREAMINGANDFORMATTING
- TASK=TAKEOVER
script:
- pyflakes bin/deepstate/*.py
- pyflakes tests/*.py
- if [ $TASK = ARITHMETIC ]; then nosetests test_arithmetic ; fi
- if [ $TASK = CRASH ]; then nosetests test_crash ; fi
- if [ $TASK = FIXTURE ]; then nosetests test_fixture ; fi
- if [ $TASK = KLEE ]; then nosetests test_klee ; fi
- if [ $TASK = LISTS ]; then nosetests test_lists ; fi
- if [ $TASK = ONEOF ]; then nosetests test_oneof ; fi
- if [ $TASK = OVERFLOW ]; then nosetests test_overflow ; fi
- if [ $TASK = PRIMES ]; then nosetests test_primes ; fi
- if [ $TASK = STREAMINGANDFORMATTING ]; then nosetests test_streamingandformatting ; fi
- if [ $TASK = TAKEOVER ]; then nosetests test_takeover ; fi

