language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- sudo apt-get -y update
- sudo apt-get -y install build-essential gcc-multilib cmake python python-setuptools libffi-dev
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo add-apt-repository -y ppa:neon1ks/xenial; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo apt-get -y update; fi
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo apt-get -y install z3; fi
- mkdir build
- cd build
- cmake ..
- make
- python setup.py install
- cd ..
env:
- TASK=ANGR DEEPSTATE_CMD=deepstate-angr
- TASK=MANTICORE DEEPSTATE_CMD=deepstate-manticore
script:
- nosetests --verbose
