language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- sudo apt-get update
- sudo apt-get install build-essential gcc-multilib cmake python python-setuptools libffi-dev
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo add-apt-repository ppa:neon1ks/xenial
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo apt-get update
- if [ $DEEPSTATE_CMD = deepstate-manticore ]; then sudo apt-get install z3
- mkdir build
- cd build
- cmake ..
- make
- python setup.py install
- cd ..
env:
- TASK=ANGR DEEPSTATE_CMD=deepstate-angr
- TASK=MANTICORE DEEPSTATE_CMD=deepstate-manticore
script:
- nosetests --verbose
