language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- sudo apt-get update
- sudo apt-get install build-essential gcc-multilib cmake python python-setuptools libffi-dev z3
- mkdir build
- cd build
- cmake ..
- make
- python setup.py install
script:
- deepstate-manticore examples/IntegerArithmetic
