language: python
dist: trusty
sudo: true
python:
- "2.7"
install:
- sudo apt-get -y update
- sudo apt-get -y install build-essential gcc-multilib cmake python python-pip python-setuptools libffi-dev
- sudo pip2 install -U pip
- sudo pip install pyflakes
- sudo pip install z3-solver
- sudo pip install https://github.com/trailofbits/manticore/archive/last_python2.zip
- sudo pip install cffi==1.7.0 pycparser==2.18 cle==7.8.9.26 pyvex==7.8.9.26 
#- sudo pip install angr==7.8.7.1
- mkdir build
- cd build
- cmake ..
- sudo make install
#- sudo pip2 uninstall -y pycparser==2.19
#- sudo pip2 install pycparser==2.18
- cd ..
env:
- TASK=ARITHMETIC
- TASK=CRASH
- TASK=FIXTURE
- TASK=KLEE
- TASK=LISTS
- TASK=ONEOF
- TASK=OVERFLOW
- TASK=PRIMES
- TASK=STREAMINGANDFORMATTING
- TASK=TAKEOVER
script:
- pyflakes bin/deepstate/*.py
- pyflakes tests/*.py
- if [ $TASK = ARITHMETIC ]; then nosetests tests/test_arithmetic.py ; fi
- if [ $TASK = CRASH ]; then nosetests tests/test_crash.py ; fi
- if [ $TASK = FIXTURE ]; then nosetests tests/test_fixture.py ; fi
- if [ $TASK = KLEE ]; then nosetests tests/test_klee.py ; fi
- if [ $TASK = LISTS ]; then nosetests tests/test_lists.py ; fi
- if [ $TASK = ONEOF ]; then nosetests tests/test_oneof.py ; fi
- if [ $TASK = OVERFLOW ]; then nosetests tests/test_overflow.py ; fi
- if [ $TASK = PRIMES ]; then nosetests tests/test_primes.py ; fi
- if [ $TASK = STREAMINGANDFORMATTING ]; then nosetests tests/test_streamingandformatting.py ; fi
- if [ $TASK = TAKEOVER ]; then nosetests tests/test_takeover.py ; fi

