name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # run CI every day even if no PRs/merges occur
    - cron:  '0 12 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyflakes mypy
      - name: Lint
        run: |
          find ./bin -name '*.py' -exec pyflakes "{}" \;
          find ./tests -name '*.py' -exec pyflakes "{}" \;
          mypy --strict-optional --config-file mypy.ini bin/deepstate
  build:
    strategy:
      matrix:
        env:
          - TEST: crash
          - TEST: fixture
          - TEST: klee
          - TEST: lists
          - TEST: oneof
          - TEST: runlen
          - TEST: runlen
          - TEST: overflow
          - TEST: primes
          - TEST: takeover
          # - TEST: streamingandformatting
          # - TEST: boringdisabled
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          sudo apt install build-essential gcc-multilib cmake libffi-dev
          python -m pip install --upgrade pip
          pip install z3-solver angr nose
          pip install git+git://github.com/trailofbits/manticore.git
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          sudo make install
      - name: Test
        run: |
          nosetests tests/test_${{ matrix.env.TEST }}.py
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Clear cache
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p  ${{ secrets.DOCKER_PASSWORD }} docker.pkg.github.com
          docker images
          docker rmi -f trailofbits/deepstate/deepstate-base
          docker rmi -f trailofbits/deepstate/deepstate
          docker images | grep trailofbits/deepstate/deepstate-base | tr -s ' ' | cut -d ' ' -f 2 | xargs -I {} docker rmi trailofbits/deepstate/deepstate-base:{}
          docker images | grep trailofbits/deepstate/deepstate | tr -s ' ' | cut -d ' ' -f 2 | xargs -I {} docker rmi trailofbits/deepstate/deepstate:{}
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          image_name: trailofbits/deepstate/deepstate-base
          image_tag: latest
          context: docker/base
          dockerfile: Dockerfile
          push_image_and_stages: true  # because we run workflow on PRs
          build_extra_args: "--tag deepstate-base"
      - uses: whoan/docker-build-with-cache-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          image_name: trailofbits/deepstate/deepstate
          image_tag: latest
          context: .
          dockerfile: docker/Dockerfile
          push_image_and_stages: true  # because we run workflow on PRs
          build_extra_args: "--cache-from=deepstate-base --build-arg=make_j=2"
      - name: Test fuzzers
        run: |
          docker run -it deepstate bash -c 'sudo pip3 install nose && \
            echo core | sudo tee /proc/sys/kernel/core_pattern && \
            echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor && \
            nosetests tests/test_fuzzers.py'
